name: auto tag

on:
  push:
    branches:
      - release

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from package.json
        id: get-version
        run: |
          VERSION=v$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git tag ${{ steps.get-version.outputs.version }}
          git push origin ${{ steps.get-version.outputs.version }}
